/* ccnetobj.c generated by valac 0.56.14, the Vala compiler
 * generated from ccnetobj.vala, do not modify */

#include <glib-object.h>
#include <glib.h>
#include <stdlib.h>
#include <string.h>

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define CCNET_TYPE_EMAIL_USER (ccnet_email_user_get_type ())
#define CCNET_EMAIL_USER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CCNET_TYPE_EMAIL_USER, CcnetEmailUser))
#define CCNET_EMAIL_USER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CCNET_TYPE_EMAIL_USER, CcnetEmailUserClass))
#define CCNET_IS_EMAIL_USER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CCNET_TYPE_EMAIL_USER))
#define CCNET_IS_EMAIL_USER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CCNET_TYPE_EMAIL_USER))
#define CCNET_EMAIL_USER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CCNET_TYPE_EMAIL_USER, CcnetEmailUserClass))

typedef struct _CcnetEmailUser CcnetEmailUser;
typedef struct _CcnetEmailUserClass CcnetEmailUserClass;
typedef struct _CcnetEmailUserPrivate CcnetEmailUserPrivate;
enum  {
	CCNET_EMAIL_USER_0_PROPERTY,
	CCNET_EMAIL_USER_ID_PROPERTY,
	CCNET_EMAIL_USER_EMAIL_PROPERTY,
	CCNET_EMAIL_USER_IS_STAFF_PROPERTY,
	CCNET_EMAIL_USER_IS_ACTIVE_PROPERTY,
	CCNET_EMAIL_USER_CTIME_PROPERTY,
	CCNET_EMAIL_USER_SOURCE_PROPERTY,
	CCNET_EMAIL_USER_ROLE_PROPERTY,
	CCNET_EMAIL_USER_PASSWORD_PROPERTY,
	CCNET_EMAIL_USER_REFERENCE_ID_PROPERTY,
	CCNET_EMAIL_USER_NUM_PROPERTIES
};
static GParamSpec* ccnet_email_user_properties[CCNET_EMAIL_USER_NUM_PROPERTIES];
#define _g_free0(var) (var = (g_free (var), NULL))

#define CCNET_TYPE_GROUP (ccnet_group_get_type ())
#define CCNET_GROUP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CCNET_TYPE_GROUP, CcnetGroup))
#define CCNET_GROUP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CCNET_TYPE_GROUP, CcnetGroupClass))
#define CCNET_IS_GROUP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CCNET_TYPE_GROUP))
#define CCNET_IS_GROUP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CCNET_TYPE_GROUP))
#define CCNET_GROUP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CCNET_TYPE_GROUP, CcnetGroupClass))

typedef struct _CcnetGroup CcnetGroup;
typedef struct _CcnetGroupClass CcnetGroupClass;
typedef struct _CcnetGroupPrivate CcnetGroupPrivate;
enum  {
	CCNET_GROUP_0_PROPERTY,
	CCNET_GROUP_ID_PROPERTY,
	CCNET_GROUP_GROUP_NAME_PROPERTY,
	CCNET_GROUP_CREATOR_NAME_PROPERTY,
	CCNET_GROUP_TIMESTAMP_PROPERTY,
	CCNET_GROUP_SOURCE_PROPERTY,
	CCNET_GROUP_PARENT_GROUP_ID_PROPERTY,
	CCNET_GROUP_NUM_PROPERTIES
};
static GParamSpec* ccnet_group_properties[CCNET_GROUP_NUM_PROPERTIES];

#define CCNET_TYPE_GROUP_USER (ccnet_group_user_get_type ())
#define CCNET_GROUP_USER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CCNET_TYPE_GROUP_USER, CcnetGroupUser))
#define CCNET_GROUP_USER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CCNET_TYPE_GROUP_USER, CcnetGroupUserClass))
#define CCNET_IS_GROUP_USER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CCNET_TYPE_GROUP_USER))
#define CCNET_IS_GROUP_USER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CCNET_TYPE_GROUP_USER))
#define CCNET_GROUP_USER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CCNET_TYPE_GROUP_USER, CcnetGroupUserClass))

typedef struct _CcnetGroupUser CcnetGroupUser;
typedef struct _CcnetGroupUserClass CcnetGroupUserClass;
typedef struct _CcnetGroupUserPrivate CcnetGroupUserPrivate;
enum  {
	CCNET_GROUP_USER_0_PROPERTY,
	CCNET_GROUP_USER_GROUP_ID_PROPERTY,
	CCNET_GROUP_USER_USER_NAME_PROPERTY,
	CCNET_GROUP_USER_IS_STAFF_PROPERTY,
	CCNET_GROUP_USER_NUM_PROPERTIES
};
static GParamSpec* ccnet_group_user_properties[CCNET_GROUP_USER_NUM_PROPERTIES];

#define CCNET_TYPE_ORGANIZATION (ccnet_organization_get_type ())
#define CCNET_ORGANIZATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CCNET_TYPE_ORGANIZATION, CcnetOrganization))
#define CCNET_ORGANIZATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CCNET_TYPE_ORGANIZATION, CcnetOrganizationClass))
#define CCNET_IS_ORGANIZATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CCNET_TYPE_ORGANIZATION))
#define CCNET_IS_ORGANIZATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CCNET_TYPE_ORGANIZATION))
#define CCNET_ORGANIZATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CCNET_TYPE_ORGANIZATION, CcnetOrganizationClass))

typedef struct _CcnetOrganization CcnetOrganization;
typedef struct _CcnetOrganizationClass CcnetOrganizationClass;
typedef struct _CcnetOrganizationPrivate CcnetOrganizationPrivate;
enum  {
	CCNET_ORGANIZATION_0_PROPERTY,
	CCNET_ORGANIZATION_ORG_ID_PROPERTY,
	CCNET_ORGANIZATION_EMAIL_PROPERTY,
	CCNET_ORGANIZATION_IS_STAFF_PROPERTY,
	CCNET_ORGANIZATION_ORG_NAME_PROPERTY,
	CCNET_ORGANIZATION_URL_PREFIX_PROPERTY,
	CCNET_ORGANIZATION_CREATOR_PROPERTY,
	CCNET_ORGANIZATION_CTIME_PROPERTY,
	CCNET_ORGANIZATION_NUM_PROPERTIES
};
static GParamSpec* ccnet_organization_properties[CCNET_ORGANIZATION_NUM_PROPERTIES];

struct _CcnetEmailUser {
	GObject parent_instance;
	CcnetEmailUserPrivate * priv;
};

struct _CcnetEmailUserClass {
	GObjectClass parent_class;
};

struct _CcnetEmailUserPrivate {
	gint _id;
	gchar* _email;
	gboolean _is_staff;
	gboolean _is_active;
	gint64 _ctime;
	gchar* _source;
	gchar* _role;
	gchar* _password;
	gchar* _reference_id;
};

struct _CcnetGroup {
	GObject parent_instance;
	CcnetGroupPrivate * priv;
};

struct _CcnetGroupClass {
	GObjectClass parent_class;
};

struct _CcnetGroupPrivate {
	gint _id;
	gchar* _group_name;
	gchar* _creator_name;
	gint64 _timestamp;
	gchar* _source;
	gint _parent_group_id;
};

struct _CcnetGroupUser {
	GObject parent_instance;
	CcnetGroupUserPrivate * priv;
};

struct _CcnetGroupUserClass {
	GObjectClass parent_class;
};

struct _CcnetGroupUserPrivate {
	gint _group_id;
	gchar* _user_name;
	gint _is_staff;
};

struct _CcnetOrganization {
	GObject parent_instance;
	CcnetOrganizationPrivate * priv;
};

struct _CcnetOrganizationClass {
	GObjectClass parent_class;
};

struct _CcnetOrganizationPrivate {
	gint _org_id;
	gchar* _email;
	gint _is_staff;
	gchar* _org_name;
	gchar* _url_prefix;
	gchar* _creator;
	gint64 _ctime;
};

static gint CcnetEmailUser_private_offset;
static gpointer ccnet_email_user_parent_class = NULL;
static gint CcnetGroup_private_offset;
static gpointer ccnet_group_parent_class = NULL;
static gint CcnetGroupUser_private_offset;
static gpointer ccnet_group_user_parent_class = NULL;
static gint CcnetOrganization_private_offset;
static gpointer ccnet_organization_parent_class = NULL;

VALA_EXTERN GType ccnet_email_user_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (CcnetEmailUser, g_object_unref)
VALA_EXTERN CcnetEmailUser* ccnet_email_user_new (void);
VALA_EXTERN CcnetEmailUser* ccnet_email_user_construct (GType object_type);
VALA_EXTERN gint ccnet_email_user_get_id (CcnetEmailUser* self);
VALA_EXTERN void ccnet_email_user_set_id (CcnetEmailUser* self,
                              gint value);
VALA_EXTERN const gchar* ccnet_email_user_get_email (CcnetEmailUser* self);
VALA_EXTERN void ccnet_email_user_set_email (CcnetEmailUser* self,
                                 const gchar* value);
VALA_EXTERN gboolean ccnet_email_user_get_is_staff (CcnetEmailUser* self);
VALA_EXTERN void ccnet_email_user_set_is_staff (CcnetEmailUser* self,
                                    gboolean value);
VALA_EXTERN gboolean ccnet_email_user_get_is_active (CcnetEmailUser* self);
VALA_EXTERN void ccnet_email_user_set_is_active (CcnetEmailUser* self,
                                     gboolean value);
VALA_EXTERN gint64 ccnet_email_user_get_ctime (CcnetEmailUser* self);
VALA_EXTERN void ccnet_email_user_set_ctime (CcnetEmailUser* self,
                                 gint64 value);
VALA_EXTERN const gchar* ccnet_email_user_get_source (CcnetEmailUser* self);
VALA_EXTERN void ccnet_email_user_set_source (CcnetEmailUser* self,
                                  const gchar* value);
VALA_EXTERN const gchar* ccnet_email_user_get_role (CcnetEmailUser* self);
VALA_EXTERN void ccnet_email_user_set_role (CcnetEmailUser* self,
                                const gchar* value);
VALA_EXTERN const gchar* ccnet_email_user_get_password (CcnetEmailUser* self);
VALA_EXTERN void ccnet_email_user_set_password (CcnetEmailUser* self,
                                    const gchar* value);
VALA_EXTERN const gchar* ccnet_email_user_get_reference_id (CcnetEmailUser* self);
VALA_EXTERN void ccnet_email_user_set_reference_id (CcnetEmailUser* self,
                                        const gchar* value);
static void ccnet_email_user_finalize (GObject * obj);
static GType ccnet_email_user_get_type_once (void);
static void _vala_ccnet_email_user_get_property (GObject * object,
                                          guint property_id,
                                          GValue * value,
                                          GParamSpec * pspec);
static void _vala_ccnet_email_user_set_property (GObject * object,
                                          guint property_id,
                                          const GValue * value,
                                          GParamSpec * pspec);
VALA_EXTERN GType ccnet_group_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (CcnetGroup, g_object_unref)
VALA_EXTERN CcnetGroup* ccnet_group_new (void);
VALA_EXTERN CcnetGroup* ccnet_group_construct (GType object_type);
VALA_EXTERN gint ccnet_group_get_id (CcnetGroup* self);
VALA_EXTERN void ccnet_group_set_id (CcnetGroup* self,
                         gint value);
VALA_EXTERN const gchar* ccnet_group_get_group_name (CcnetGroup* self);
VALA_EXTERN void ccnet_group_set_group_name (CcnetGroup* self,
                                 const gchar* value);
VALA_EXTERN const gchar* ccnet_group_get_creator_name (CcnetGroup* self);
VALA_EXTERN void ccnet_group_set_creator_name (CcnetGroup* self,
                                   const gchar* value);
VALA_EXTERN gint64 ccnet_group_get_timestamp (CcnetGroup* self);
VALA_EXTERN void ccnet_group_set_timestamp (CcnetGroup* self,
                                gint64 value);
VALA_EXTERN const gchar* ccnet_group_get_source (CcnetGroup* self);
VALA_EXTERN void ccnet_group_set_source (CcnetGroup* self,
                             const gchar* value);
VALA_EXTERN gint ccnet_group_get_parent_group_id (CcnetGroup* self);
VALA_EXTERN void ccnet_group_set_parent_group_id (CcnetGroup* self,
                                      gint value);
static void ccnet_group_finalize (GObject * obj);
static GType ccnet_group_get_type_once (void);
static void _vala_ccnet_group_get_property (GObject * object,
                                     guint property_id,
                                     GValue * value,
                                     GParamSpec * pspec);
static void _vala_ccnet_group_set_property (GObject * object,
                                     guint property_id,
                                     const GValue * value,
                                     GParamSpec * pspec);
VALA_EXTERN GType ccnet_group_user_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (CcnetGroupUser, g_object_unref)
VALA_EXTERN CcnetGroupUser* ccnet_group_user_new (void);
VALA_EXTERN CcnetGroupUser* ccnet_group_user_construct (GType object_type);
VALA_EXTERN gint ccnet_group_user_get_group_id (CcnetGroupUser* self);
VALA_EXTERN void ccnet_group_user_set_group_id (CcnetGroupUser* self,
                                    gint value);
VALA_EXTERN const gchar* ccnet_group_user_get_user_name (CcnetGroupUser* self);
VALA_EXTERN void ccnet_group_user_set_user_name (CcnetGroupUser* self,
                                     const gchar* value);
VALA_EXTERN gint ccnet_group_user_get_is_staff (CcnetGroupUser* self);
VALA_EXTERN void ccnet_group_user_set_is_staff (CcnetGroupUser* self,
                                    gint value);
static void ccnet_group_user_finalize (GObject * obj);
static GType ccnet_group_user_get_type_once (void);
static void _vala_ccnet_group_user_get_property (GObject * object,
                                          guint property_id,
                                          GValue * value,
                                          GParamSpec * pspec);
static void _vala_ccnet_group_user_set_property (GObject * object,
                                          guint property_id,
                                          const GValue * value,
                                          GParamSpec * pspec);
VALA_EXTERN GType ccnet_organization_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (CcnetOrganization, g_object_unref)
VALA_EXTERN CcnetOrganization* ccnet_organization_new (void);
VALA_EXTERN CcnetOrganization* ccnet_organization_construct (GType object_type);
VALA_EXTERN gint ccnet_organization_get_org_id (CcnetOrganization* self);
VALA_EXTERN void ccnet_organization_set_org_id (CcnetOrganization* self,
                                    gint value);
VALA_EXTERN const gchar* ccnet_organization_get_email (CcnetOrganization* self);
VALA_EXTERN void ccnet_organization_set_email (CcnetOrganization* self,
                                   const gchar* value);
VALA_EXTERN gint ccnet_organization_get_is_staff (CcnetOrganization* self);
VALA_EXTERN void ccnet_organization_set_is_staff (CcnetOrganization* self,
                                      gint value);
VALA_EXTERN const gchar* ccnet_organization_get_org_name (CcnetOrganization* self);
VALA_EXTERN void ccnet_organization_set_org_name (CcnetOrganization* self,
                                      const gchar* value);
VALA_EXTERN const gchar* ccnet_organization_get_url_prefix (CcnetOrganization* self);
VALA_EXTERN void ccnet_organization_set_url_prefix (CcnetOrganization* self,
                                        const gchar* value);
VALA_EXTERN const gchar* ccnet_organization_get_creator (CcnetOrganization* self);
VALA_EXTERN void ccnet_organization_set_creator (CcnetOrganization* self,
                                     const gchar* value);
VALA_EXTERN gint64 ccnet_organization_get_ctime (CcnetOrganization* self);
VALA_EXTERN void ccnet_organization_set_ctime (CcnetOrganization* self,
                                   gint64 value);
static void ccnet_organization_finalize (GObject * obj);
static GType ccnet_organization_get_type_once (void);
static void _vala_ccnet_organization_get_property (GObject * object,
                                            guint property_id,
                                            GValue * value,
                                            GParamSpec * pspec);
static void _vala_ccnet_organization_set_property (GObject * object,
                                            guint property_id,
                                            const GValue * value,
                                            GParamSpec * pspec);

static inline gpointer
ccnet_email_user_get_instance_private (CcnetEmailUser* self)
{
	return G_STRUCT_MEMBER_P (self, CcnetEmailUser_private_offset);
}

CcnetEmailUser*
ccnet_email_user_construct (GType object_type)
{
	CcnetEmailUser * self = NULL;
	self = (CcnetEmailUser*) g_object_new (object_type, NULL);
	return self;
}

CcnetEmailUser*
ccnet_email_user_new (void)
{
	return ccnet_email_user_construct (CCNET_TYPE_EMAIL_USER);
}

gint
ccnet_email_user_get_id (CcnetEmailUser* self)
{
	gint result;
	g_return_val_if_fail (self != NULL, 0);
	result = self->priv->_id;
	return result;
}

void
ccnet_email_user_set_id (CcnetEmailUser* self,
                         gint value)
{
	gint old_value;
	g_return_if_fail (self != NULL);
	old_value = ccnet_email_user_get_id (self);
	if (old_value != value) {
		self->priv->_id = value;
		g_object_notify_by_pspec ((GObject *) self, ccnet_email_user_properties[CCNET_EMAIL_USER_ID_PROPERTY]);
	}
}

const gchar*
ccnet_email_user_get_email (CcnetEmailUser* self)
{
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_email;
	result = _tmp0_;
	return result;
}

void
ccnet_email_user_set_email (CcnetEmailUser* self,
                            const gchar* value)
{
	gchar* old_value;
	g_return_if_fail (self != NULL);
	old_value = ccnet_email_user_get_email (self);
	if (g_strcmp0 (value, old_value) != 0) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (value);
		_g_free0 (self->priv->_email);
		self->priv->_email = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, ccnet_email_user_properties[CCNET_EMAIL_USER_EMAIL_PROPERTY]);
	}
}

gboolean
ccnet_email_user_get_is_staff (CcnetEmailUser* self)
{
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = self->priv->_is_staff;
	return result;
}

void
ccnet_email_user_set_is_staff (CcnetEmailUser* self,
                               gboolean value)
{
	gboolean old_value;
	g_return_if_fail (self != NULL);
	old_value = ccnet_email_user_get_is_staff (self);
	if (old_value != value) {
		self->priv->_is_staff = value;
		g_object_notify_by_pspec ((GObject *) self, ccnet_email_user_properties[CCNET_EMAIL_USER_IS_STAFF_PROPERTY]);
	}
}

gboolean
ccnet_email_user_get_is_active (CcnetEmailUser* self)
{
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = self->priv->_is_active;
	return result;
}

void
ccnet_email_user_set_is_active (CcnetEmailUser* self,
                                gboolean value)
{
	gboolean old_value;
	g_return_if_fail (self != NULL);
	old_value = ccnet_email_user_get_is_active (self);
	if (old_value != value) {
		self->priv->_is_active = value;
		g_object_notify_by_pspec ((GObject *) self, ccnet_email_user_properties[CCNET_EMAIL_USER_IS_ACTIVE_PROPERTY]);
	}
}

gint64
ccnet_email_user_get_ctime (CcnetEmailUser* self)
{
	gint64 result;
	g_return_val_if_fail (self != NULL, 0LL);
	result = self->priv->_ctime;
	return result;
}

void
ccnet_email_user_set_ctime (CcnetEmailUser* self,
                            gint64 value)
{
	gint64 old_value;
	g_return_if_fail (self != NULL);
	old_value = ccnet_email_user_get_ctime (self);
	if (old_value != value) {
		self->priv->_ctime = value;
		g_object_notify_by_pspec ((GObject *) self, ccnet_email_user_properties[CCNET_EMAIL_USER_CTIME_PROPERTY]);
	}
}

const gchar*
ccnet_email_user_get_source (CcnetEmailUser* self)
{
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_source;
	result = _tmp0_;
	return result;
}

void
ccnet_email_user_set_source (CcnetEmailUser* self,
                             const gchar* value)
{
	gchar* old_value;
	g_return_if_fail (self != NULL);
	old_value = ccnet_email_user_get_source (self);
	if (g_strcmp0 (value, old_value) != 0) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (value);
		_g_free0 (self->priv->_source);
		self->priv->_source = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, ccnet_email_user_properties[CCNET_EMAIL_USER_SOURCE_PROPERTY]);
	}
}

const gchar*
ccnet_email_user_get_role (CcnetEmailUser* self)
{
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_role;
	result = _tmp0_;
	return result;
}

void
ccnet_email_user_set_role (CcnetEmailUser* self,
                           const gchar* value)
{
	gchar* old_value;
	g_return_if_fail (self != NULL);
	old_value = ccnet_email_user_get_role (self);
	if (g_strcmp0 (value, old_value) != 0) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (value);
		_g_free0 (self->priv->_role);
		self->priv->_role = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, ccnet_email_user_properties[CCNET_EMAIL_USER_ROLE_PROPERTY]);
	}
}

const gchar*
ccnet_email_user_get_password (CcnetEmailUser* self)
{
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_password;
	result = _tmp0_;
	return result;
}

void
ccnet_email_user_set_password (CcnetEmailUser* self,
                               const gchar* value)
{
	gchar* old_value;
	g_return_if_fail (self != NULL);
	old_value = ccnet_email_user_get_password (self);
	if (g_strcmp0 (value, old_value) != 0) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (value);
		_g_free0 (self->priv->_password);
		self->priv->_password = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, ccnet_email_user_properties[CCNET_EMAIL_USER_PASSWORD_PROPERTY]);
	}
}

const gchar*
ccnet_email_user_get_reference_id (CcnetEmailUser* self)
{
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_reference_id;
	result = _tmp0_;
	return result;
}

void
ccnet_email_user_set_reference_id (CcnetEmailUser* self,
                                   const gchar* value)
{
	gchar* old_value;
	g_return_if_fail (self != NULL);
	old_value = ccnet_email_user_get_reference_id (self);
	if (g_strcmp0 (value, old_value) != 0) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (value);
		_g_free0 (self->priv->_reference_id);
		self->priv->_reference_id = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, ccnet_email_user_properties[CCNET_EMAIL_USER_REFERENCE_ID_PROPERTY]);
	}
}

static void
ccnet_email_user_class_init (CcnetEmailUserClass * klass,
                             gpointer klass_data)
{
	ccnet_email_user_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &CcnetEmailUser_private_offset);
	G_OBJECT_CLASS (klass)->get_property = _vala_ccnet_email_user_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_ccnet_email_user_set_property;
	G_OBJECT_CLASS (klass)->finalize = ccnet_email_user_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_EMAIL_USER_ID_PROPERTY, ccnet_email_user_properties[CCNET_EMAIL_USER_ID_PROPERTY] = g_param_spec_int ("id", "id", "id", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_EMAIL_USER_EMAIL_PROPERTY, ccnet_email_user_properties[CCNET_EMAIL_USER_EMAIL_PROPERTY] = g_param_spec_string ("email", "email", "email", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_EMAIL_USER_IS_STAFF_PROPERTY, ccnet_email_user_properties[CCNET_EMAIL_USER_IS_STAFF_PROPERTY] = g_param_spec_boolean ("is-staff", "is-staff", "is-staff", FALSE, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_EMAIL_USER_IS_ACTIVE_PROPERTY, ccnet_email_user_properties[CCNET_EMAIL_USER_IS_ACTIVE_PROPERTY] = g_param_spec_boolean ("is-active", "is-active", "is-active", FALSE, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_EMAIL_USER_CTIME_PROPERTY, ccnet_email_user_properties[CCNET_EMAIL_USER_CTIME_PROPERTY] = g_param_spec_int64 ("ctime", "ctime", "ctime", G_MININT64, G_MAXINT64, 0, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_EMAIL_USER_SOURCE_PROPERTY, ccnet_email_user_properties[CCNET_EMAIL_USER_SOURCE_PROPERTY] = g_param_spec_string ("source", "source", "source", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_EMAIL_USER_ROLE_PROPERTY, ccnet_email_user_properties[CCNET_EMAIL_USER_ROLE_PROPERTY] = g_param_spec_string ("role", "role", "role", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_EMAIL_USER_PASSWORD_PROPERTY, ccnet_email_user_properties[CCNET_EMAIL_USER_PASSWORD_PROPERTY] = g_param_spec_string ("password", "password", "password", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_EMAIL_USER_REFERENCE_ID_PROPERTY, ccnet_email_user_properties[CCNET_EMAIL_USER_REFERENCE_ID_PROPERTY] = g_param_spec_string ("reference-id", "reference-id", "reference-id", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
}

static void
ccnet_email_user_instance_init (CcnetEmailUser * self,
                                gpointer klass)
{
	self->priv = ccnet_email_user_get_instance_private (self);
}

static void
ccnet_email_user_finalize (GObject * obj)
{
	CcnetEmailUser * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CCNET_TYPE_EMAIL_USER, CcnetEmailUser);
	_g_free0 (self->priv->_email);
	_g_free0 (self->priv->_source);
	_g_free0 (self->priv->_role);
	_g_free0 (self->priv->_password);
	_g_free0 (self->priv->_reference_id);
	G_OBJECT_CLASS (ccnet_email_user_parent_class)->finalize (obj);
}

static GType
ccnet_email_user_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (CcnetEmailUserClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) ccnet_email_user_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (CcnetEmailUser), 0, (GInstanceInitFunc) ccnet_email_user_instance_init, NULL };
	GType ccnet_email_user_type_id;
	ccnet_email_user_type_id = g_type_register_static (G_TYPE_OBJECT, "CcnetEmailUser", &g_define_type_info, 0);
	CcnetEmailUser_private_offset = g_type_add_instance_private (ccnet_email_user_type_id, sizeof (CcnetEmailUserPrivate));
	return ccnet_email_user_type_id;
}

GType
ccnet_email_user_get_type (void)
{
	static volatile gsize ccnet_email_user_type_id__once = 0;
	if (g_once_init_enter (&ccnet_email_user_type_id__once)) {
		GType ccnet_email_user_type_id;
		ccnet_email_user_type_id = ccnet_email_user_get_type_once ();
		g_once_init_leave (&ccnet_email_user_type_id__once, ccnet_email_user_type_id);
	}
	return ccnet_email_user_type_id__once;
}

static void
_vala_ccnet_email_user_get_property (GObject * object,
                                     guint property_id,
                                     GValue * value,
                                     GParamSpec * pspec)
{
	CcnetEmailUser * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, CCNET_TYPE_EMAIL_USER, CcnetEmailUser);
	switch (property_id) {
		case CCNET_EMAIL_USER_ID_PROPERTY:
		g_value_set_int (value, ccnet_email_user_get_id (self));
		break;
		case CCNET_EMAIL_USER_EMAIL_PROPERTY:
		g_value_set_string (value, ccnet_email_user_get_email (self));
		break;
		case CCNET_EMAIL_USER_IS_STAFF_PROPERTY:
		g_value_set_boolean (value, ccnet_email_user_get_is_staff (self));
		break;
		case CCNET_EMAIL_USER_IS_ACTIVE_PROPERTY:
		g_value_set_boolean (value, ccnet_email_user_get_is_active (self));
		break;
		case CCNET_EMAIL_USER_CTIME_PROPERTY:
		g_value_set_int64 (value, ccnet_email_user_get_ctime (self));
		break;
		case CCNET_EMAIL_USER_SOURCE_PROPERTY:
		g_value_set_string (value, ccnet_email_user_get_source (self));
		break;
		case CCNET_EMAIL_USER_ROLE_PROPERTY:
		g_value_set_string (value, ccnet_email_user_get_role (self));
		break;
		case CCNET_EMAIL_USER_PASSWORD_PROPERTY:
		g_value_set_string (value, ccnet_email_user_get_password (self));
		break;
		case CCNET_EMAIL_USER_REFERENCE_ID_PROPERTY:
		g_value_set_string (value, ccnet_email_user_get_reference_id (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

static void
_vala_ccnet_email_user_set_property (GObject * object,
                                     guint property_id,
                                     const GValue * value,
                                     GParamSpec * pspec)
{
	CcnetEmailUser * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, CCNET_TYPE_EMAIL_USER, CcnetEmailUser);
	switch (property_id) {
		case CCNET_EMAIL_USER_ID_PROPERTY:
		ccnet_email_user_set_id (self, g_value_get_int (value));
		break;
		case CCNET_EMAIL_USER_EMAIL_PROPERTY:
		ccnet_email_user_set_email (self, g_value_get_string (value));
		break;
		case CCNET_EMAIL_USER_IS_STAFF_PROPERTY:
		ccnet_email_user_set_is_staff (self, g_value_get_boolean (value));
		break;
		case CCNET_EMAIL_USER_IS_ACTIVE_PROPERTY:
		ccnet_email_user_set_is_active (self, g_value_get_boolean (value));
		break;
		case CCNET_EMAIL_USER_CTIME_PROPERTY:
		ccnet_email_user_set_ctime (self, g_value_get_int64 (value));
		break;
		case CCNET_EMAIL_USER_SOURCE_PROPERTY:
		ccnet_email_user_set_source (self, g_value_get_string (value));
		break;
		case CCNET_EMAIL_USER_ROLE_PROPERTY:
		ccnet_email_user_set_role (self, g_value_get_string (value));
		break;
		case CCNET_EMAIL_USER_PASSWORD_PROPERTY:
		ccnet_email_user_set_password (self, g_value_get_string (value));
		break;
		case CCNET_EMAIL_USER_REFERENCE_ID_PROPERTY:
		ccnet_email_user_set_reference_id (self, g_value_get_string (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

static inline gpointer
ccnet_group_get_instance_private (CcnetGroup* self)
{
	return G_STRUCT_MEMBER_P (self, CcnetGroup_private_offset);
}

CcnetGroup*
ccnet_group_construct (GType object_type)
{
	CcnetGroup * self = NULL;
	self = (CcnetGroup*) g_object_new (object_type, NULL);
	return self;
}

CcnetGroup*
ccnet_group_new (void)
{
	return ccnet_group_construct (CCNET_TYPE_GROUP);
}

gint
ccnet_group_get_id (CcnetGroup* self)
{
	gint result;
	g_return_val_if_fail (self != NULL, 0);
	result = self->priv->_id;
	return result;
}

void
ccnet_group_set_id (CcnetGroup* self,
                    gint value)
{
	gint old_value;
	g_return_if_fail (self != NULL);
	old_value = ccnet_group_get_id (self);
	if (old_value != value) {
		self->priv->_id = value;
		g_object_notify_by_pspec ((GObject *) self, ccnet_group_properties[CCNET_GROUP_ID_PROPERTY]);
	}
}

const gchar*
ccnet_group_get_group_name (CcnetGroup* self)
{
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_group_name;
	result = _tmp0_;
	return result;
}

void
ccnet_group_set_group_name (CcnetGroup* self,
                            const gchar* value)
{
	gchar* old_value;
	g_return_if_fail (self != NULL);
	old_value = ccnet_group_get_group_name (self);
	if (g_strcmp0 (value, old_value) != 0) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (value);
		_g_free0 (self->priv->_group_name);
		self->priv->_group_name = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, ccnet_group_properties[CCNET_GROUP_GROUP_NAME_PROPERTY]);
	}
}

const gchar*
ccnet_group_get_creator_name (CcnetGroup* self)
{
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_creator_name;
	result = _tmp0_;
	return result;
}

void
ccnet_group_set_creator_name (CcnetGroup* self,
                              const gchar* value)
{
	gchar* old_value;
	g_return_if_fail (self != NULL);
	old_value = ccnet_group_get_creator_name (self);
	if (g_strcmp0 (value, old_value) != 0) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (value);
		_g_free0 (self->priv->_creator_name);
		self->priv->_creator_name = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, ccnet_group_properties[CCNET_GROUP_CREATOR_NAME_PROPERTY]);
	}
}

gint64
ccnet_group_get_timestamp (CcnetGroup* self)
{
	gint64 result;
	g_return_val_if_fail (self != NULL, 0LL);
	result = self->priv->_timestamp;
	return result;
}

void
ccnet_group_set_timestamp (CcnetGroup* self,
                           gint64 value)
{
	gint64 old_value;
	g_return_if_fail (self != NULL);
	old_value = ccnet_group_get_timestamp (self);
	if (old_value != value) {
		self->priv->_timestamp = value;
		g_object_notify_by_pspec ((GObject *) self, ccnet_group_properties[CCNET_GROUP_TIMESTAMP_PROPERTY]);
	}
}

const gchar*
ccnet_group_get_source (CcnetGroup* self)
{
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_source;
	result = _tmp0_;
	return result;
}

void
ccnet_group_set_source (CcnetGroup* self,
                        const gchar* value)
{
	gchar* old_value;
	g_return_if_fail (self != NULL);
	old_value = ccnet_group_get_source (self);
	if (g_strcmp0 (value, old_value) != 0) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (value);
		_g_free0 (self->priv->_source);
		self->priv->_source = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, ccnet_group_properties[CCNET_GROUP_SOURCE_PROPERTY]);
	}
}

gint
ccnet_group_get_parent_group_id (CcnetGroup* self)
{
	gint result;
	g_return_val_if_fail (self != NULL, 0);
	result = self->priv->_parent_group_id;
	return result;
}

void
ccnet_group_set_parent_group_id (CcnetGroup* self,
                                 gint value)
{
	gint old_value;
	g_return_if_fail (self != NULL);
	old_value = ccnet_group_get_parent_group_id (self);
	if (old_value != value) {
		self->priv->_parent_group_id = value;
		g_object_notify_by_pspec ((GObject *) self, ccnet_group_properties[CCNET_GROUP_PARENT_GROUP_ID_PROPERTY]);
	}
}

static void
ccnet_group_class_init (CcnetGroupClass * klass,
                        gpointer klass_data)
{
	ccnet_group_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &CcnetGroup_private_offset);
	G_OBJECT_CLASS (klass)->get_property = _vala_ccnet_group_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_ccnet_group_set_property;
	G_OBJECT_CLASS (klass)->finalize = ccnet_group_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_GROUP_ID_PROPERTY, ccnet_group_properties[CCNET_GROUP_ID_PROPERTY] = g_param_spec_int ("id", "id", "id", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_GROUP_GROUP_NAME_PROPERTY, ccnet_group_properties[CCNET_GROUP_GROUP_NAME_PROPERTY] = g_param_spec_string ("group-name", "group-name", "group-name", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_GROUP_CREATOR_NAME_PROPERTY, ccnet_group_properties[CCNET_GROUP_CREATOR_NAME_PROPERTY] = g_param_spec_string ("creator-name", "creator-name", "creator-name", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_GROUP_TIMESTAMP_PROPERTY, ccnet_group_properties[CCNET_GROUP_TIMESTAMP_PROPERTY] = g_param_spec_int64 ("timestamp", "timestamp", "timestamp", G_MININT64, G_MAXINT64, 0, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_GROUP_SOURCE_PROPERTY, ccnet_group_properties[CCNET_GROUP_SOURCE_PROPERTY] = g_param_spec_string ("source", "source", "source", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_GROUP_PARENT_GROUP_ID_PROPERTY, ccnet_group_properties[CCNET_GROUP_PARENT_GROUP_ID_PROPERTY] = g_param_spec_int ("parent-group-id", "parent-group-id", "parent-group-id", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
}

static void
ccnet_group_instance_init (CcnetGroup * self,
                           gpointer klass)
{
	self->priv = ccnet_group_get_instance_private (self);
}

static void
ccnet_group_finalize (GObject * obj)
{
	CcnetGroup * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CCNET_TYPE_GROUP, CcnetGroup);
	_g_free0 (self->priv->_group_name);
	_g_free0 (self->priv->_creator_name);
	_g_free0 (self->priv->_source);
	G_OBJECT_CLASS (ccnet_group_parent_class)->finalize (obj);
}

static GType
ccnet_group_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (CcnetGroupClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) ccnet_group_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (CcnetGroup), 0, (GInstanceInitFunc) ccnet_group_instance_init, NULL };
	GType ccnet_group_type_id;
	ccnet_group_type_id = g_type_register_static (G_TYPE_OBJECT, "CcnetGroup", &g_define_type_info, 0);
	CcnetGroup_private_offset = g_type_add_instance_private (ccnet_group_type_id, sizeof (CcnetGroupPrivate));
	return ccnet_group_type_id;
}

GType
ccnet_group_get_type (void)
{
	static volatile gsize ccnet_group_type_id__once = 0;
	if (g_once_init_enter (&ccnet_group_type_id__once)) {
		GType ccnet_group_type_id;
		ccnet_group_type_id = ccnet_group_get_type_once ();
		g_once_init_leave (&ccnet_group_type_id__once, ccnet_group_type_id);
	}
	return ccnet_group_type_id__once;
}

static void
_vala_ccnet_group_get_property (GObject * object,
                                guint property_id,
                                GValue * value,
                                GParamSpec * pspec)
{
	CcnetGroup * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, CCNET_TYPE_GROUP, CcnetGroup);
	switch (property_id) {
		case CCNET_GROUP_ID_PROPERTY:
		g_value_set_int (value, ccnet_group_get_id (self));
		break;
		case CCNET_GROUP_GROUP_NAME_PROPERTY:
		g_value_set_string (value, ccnet_group_get_group_name (self));
		break;
		case CCNET_GROUP_CREATOR_NAME_PROPERTY:
		g_value_set_string (value, ccnet_group_get_creator_name (self));
		break;
		case CCNET_GROUP_TIMESTAMP_PROPERTY:
		g_value_set_int64 (value, ccnet_group_get_timestamp (self));
		break;
		case CCNET_GROUP_SOURCE_PROPERTY:
		g_value_set_string (value, ccnet_group_get_source (self));
		break;
		case CCNET_GROUP_PARENT_GROUP_ID_PROPERTY:
		g_value_set_int (value, ccnet_group_get_parent_group_id (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

static void
_vala_ccnet_group_set_property (GObject * object,
                                guint property_id,
                                const GValue * value,
                                GParamSpec * pspec)
{
	CcnetGroup * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, CCNET_TYPE_GROUP, CcnetGroup);
	switch (property_id) {
		case CCNET_GROUP_ID_PROPERTY:
		ccnet_group_set_id (self, g_value_get_int (value));
		break;
		case CCNET_GROUP_GROUP_NAME_PROPERTY:
		ccnet_group_set_group_name (self, g_value_get_string (value));
		break;
		case CCNET_GROUP_CREATOR_NAME_PROPERTY:
		ccnet_group_set_creator_name (self, g_value_get_string (value));
		break;
		case CCNET_GROUP_TIMESTAMP_PROPERTY:
		ccnet_group_set_timestamp (self, g_value_get_int64 (value));
		break;
		case CCNET_GROUP_SOURCE_PROPERTY:
		ccnet_group_set_source (self, g_value_get_string (value));
		break;
		case CCNET_GROUP_PARENT_GROUP_ID_PROPERTY:
		ccnet_group_set_parent_group_id (self, g_value_get_int (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

static inline gpointer
ccnet_group_user_get_instance_private (CcnetGroupUser* self)
{
	return G_STRUCT_MEMBER_P (self, CcnetGroupUser_private_offset);
}

CcnetGroupUser*
ccnet_group_user_construct (GType object_type)
{
	CcnetGroupUser * self = NULL;
	self = (CcnetGroupUser*) g_object_new (object_type, NULL);
	return self;
}

CcnetGroupUser*
ccnet_group_user_new (void)
{
	return ccnet_group_user_construct (CCNET_TYPE_GROUP_USER);
}

gint
ccnet_group_user_get_group_id (CcnetGroupUser* self)
{
	gint result;
	g_return_val_if_fail (self != NULL, 0);
	result = self->priv->_group_id;
	return result;
}

void
ccnet_group_user_set_group_id (CcnetGroupUser* self,
                               gint value)
{
	gint old_value;
	g_return_if_fail (self != NULL);
	old_value = ccnet_group_user_get_group_id (self);
	if (old_value != value) {
		self->priv->_group_id = value;
		g_object_notify_by_pspec ((GObject *) self, ccnet_group_user_properties[CCNET_GROUP_USER_GROUP_ID_PROPERTY]);
	}
}

const gchar*
ccnet_group_user_get_user_name (CcnetGroupUser* self)
{
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_user_name;
	result = _tmp0_;
	return result;
}

void
ccnet_group_user_set_user_name (CcnetGroupUser* self,
                                const gchar* value)
{
	gchar* old_value;
	g_return_if_fail (self != NULL);
	old_value = ccnet_group_user_get_user_name (self);
	if (g_strcmp0 (value, old_value) != 0) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (value);
		_g_free0 (self->priv->_user_name);
		self->priv->_user_name = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, ccnet_group_user_properties[CCNET_GROUP_USER_USER_NAME_PROPERTY]);
	}
}

gint
ccnet_group_user_get_is_staff (CcnetGroupUser* self)
{
	gint result;
	g_return_val_if_fail (self != NULL, 0);
	result = self->priv->_is_staff;
	return result;
}

void
ccnet_group_user_set_is_staff (CcnetGroupUser* self,
                               gint value)
{
	gint old_value;
	g_return_if_fail (self != NULL);
	old_value = ccnet_group_user_get_is_staff (self);
	if (old_value != value) {
		self->priv->_is_staff = value;
		g_object_notify_by_pspec ((GObject *) self, ccnet_group_user_properties[CCNET_GROUP_USER_IS_STAFF_PROPERTY]);
	}
}

static void
ccnet_group_user_class_init (CcnetGroupUserClass * klass,
                             gpointer klass_data)
{
	ccnet_group_user_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &CcnetGroupUser_private_offset);
	G_OBJECT_CLASS (klass)->get_property = _vala_ccnet_group_user_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_ccnet_group_user_set_property;
	G_OBJECT_CLASS (klass)->finalize = ccnet_group_user_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_GROUP_USER_GROUP_ID_PROPERTY, ccnet_group_user_properties[CCNET_GROUP_USER_GROUP_ID_PROPERTY] = g_param_spec_int ("group-id", "group-id", "group-id", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_GROUP_USER_USER_NAME_PROPERTY, ccnet_group_user_properties[CCNET_GROUP_USER_USER_NAME_PROPERTY] = g_param_spec_string ("user-name", "user-name", "user-name", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_GROUP_USER_IS_STAFF_PROPERTY, ccnet_group_user_properties[CCNET_GROUP_USER_IS_STAFF_PROPERTY] = g_param_spec_int ("is-staff", "is-staff", "is-staff", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
}

static void
ccnet_group_user_instance_init (CcnetGroupUser * self,
                                gpointer klass)
{
	self->priv = ccnet_group_user_get_instance_private (self);
}

static void
ccnet_group_user_finalize (GObject * obj)
{
	CcnetGroupUser * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CCNET_TYPE_GROUP_USER, CcnetGroupUser);
	_g_free0 (self->priv->_user_name);
	G_OBJECT_CLASS (ccnet_group_user_parent_class)->finalize (obj);
}

static GType
ccnet_group_user_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (CcnetGroupUserClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) ccnet_group_user_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (CcnetGroupUser), 0, (GInstanceInitFunc) ccnet_group_user_instance_init, NULL };
	GType ccnet_group_user_type_id;
	ccnet_group_user_type_id = g_type_register_static (G_TYPE_OBJECT, "CcnetGroupUser", &g_define_type_info, 0);
	CcnetGroupUser_private_offset = g_type_add_instance_private (ccnet_group_user_type_id, sizeof (CcnetGroupUserPrivate));
	return ccnet_group_user_type_id;
}

GType
ccnet_group_user_get_type (void)
{
	static volatile gsize ccnet_group_user_type_id__once = 0;
	if (g_once_init_enter (&ccnet_group_user_type_id__once)) {
		GType ccnet_group_user_type_id;
		ccnet_group_user_type_id = ccnet_group_user_get_type_once ();
		g_once_init_leave (&ccnet_group_user_type_id__once, ccnet_group_user_type_id);
	}
	return ccnet_group_user_type_id__once;
}

static void
_vala_ccnet_group_user_get_property (GObject * object,
                                     guint property_id,
                                     GValue * value,
                                     GParamSpec * pspec)
{
	CcnetGroupUser * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, CCNET_TYPE_GROUP_USER, CcnetGroupUser);
	switch (property_id) {
		case CCNET_GROUP_USER_GROUP_ID_PROPERTY:
		g_value_set_int (value, ccnet_group_user_get_group_id (self));
		break;
		case CCNET_GROUP_USER_USER_NAME_PROPERTY:
		g_value_set_string (value, ccnet_group_user_get_user_name (self));
		break;
		case CCNET_GROUP_USER_IS_STAFF_PROPERTY:
		g_value_set_int (value, ccnet_group_user_get_is_staff (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

static void
_vala_ccnet_group_user_set_property (GObject * object,
                                     guint property_id,
                                     const GValue * value,
                                     GParamSpec * pspec)
{
	CcnetGroupUser * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, CCNET_TYPE_GROUP_USER, CcnetGroupUser);
	switch (property_id) {
		case CCNET_GROUP_USER_GROUP_ID_PROPERTY:
		ccnet_group_user_set_group_id (self, g_value_get_int (value));
		break;
		case CCNET_GROUP_USER_USER_NAME_PROPERTY:
		ccnet_group_user_set_user_name (self, g_value_get_string (value));
		break;
		case CCNET_GROUP_USER_IS_STAFF_PROPERTY:
		ccnet_group_user_set_is_staff (self, g_value_get_int (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

static inline gpointer
ccnet_organization_get_instance_private (CcnetOrganization* self)
{
	return G_STRUCT_MEMBER_P (self, CcnetOrganization_private_offset);
}

CcnetOrganization*
ccnet_organization_construct (GType object_type)
{
	CcnetOrganization * self = NULL;
	self = (CcnetOrganization*) g_object_new (object_type, NULL);
	return self;
}

CcnetOrganization*
ccnet_organization_new (void)
{
	return ccnet_organization_construct (CCNET_TYPE_ORGANIZATION);
}

gint
ccnet_organization_get_org_id (CcnetOrganization* self)
{
	gint result;
	g_return_val_if_fail (self != NULL, 0);
	result = self->priv->_org_id;
	return result;
}

void
ccnet_organization_set_org_id (CcnetOrganization* self,
                               gint value)
{
	gint old_value;
	g_return_if_fail (self != NULL);
	old_value = ccnet_organization_get_org_id (self);
	if (old_value != value) {
		self->priv->_org_id = value;
		g_object_notify_by_pspec ((GObject *) self, ccnet_organization_properties[CCNET_ORGANIZATION_ORG_ID_PROPERTY]);
	}
}

const gchar*
ccnet_organization_get_email (CcnetOrganization* self)
{
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_email;
	result = _tmp0_;
	return result;
}

void
ccnet_organization_set_email (CcnetOrganization* self,
                              const gchar* value)
{
	gchar* old_value;
	g_return_if_fail (self != NULL);
	old_value = ccnet_organization_get_email (self);
	if (g_strcmp0 (value, old_value) != 0) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (value);
		_g_free0 (self->priv->_email);
		self->priv->_email = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, ccnet_organization_properties[CCNET_ORGANIZATION_EMAIL_PROPERTY]);
	}
}

gint
ccnet_organization_get_is_staff (CcnetOrganization* self)
{
	gint result;
	g_return_val_if_fail (self != NULL, 0);
	result = self->priv->_is_staff;
	return result;
}

void
ccnet_organization_set_is_staff (CcnetOrganization* self,
                                 gint value)
{
	gint old_value;
	g_return_if_fail (self != NULL);
	old_value = ccnet_organization_get_is_staff (self);
	if (old_value != value) {
		self->priv->_is_staff = value;
		g_object_notify_by_pspec ((GObject *) self, ccnet_organization_properties[CCNET_ORGANIZATION_IS_STAFF_PROPERTY]);
	}
}

const gchar*
ccnet_organization_get_org_name (CcnetOrganization* self)
{
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_org_name;
	result = _tmp0_;
	return result;
}

void
ccnet_organization_set_org_name (CcnetOrganization* self,
                                 const gchar* value)
{
	gchar* old_value;
	g_return_if_fail (self != NULL);
	old_value = ccnet_organization_get_org_name (self);
	if (g_strcmp0 (value, old_value) != 0) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (value);
		_g_free0 (self->priv->_org_name);
		self->priv->_org_name = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, ccnet_organization_properties[CCNET_ORGANIZATION_ORG_NAME_PROPERTY]);
	}
}

const gchar*
ccnet_organization_get_url_prefix (CcnetOrganization* self)
{
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_url_prefix;
	result = _tmp0_;
	return result;
}

void
ccnet_organization_set_url_prefix (CcnetOrganization* self,
                                   const gchar* value)
{
	gchar* old_value;
	g_return_if_fail (self != NULL);
	old_value = ccnet_organization_get_url_prefix (self);
	if (g_strcmp0 (value, old_value) != 0) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (value);
		_g_free0 (self->priv->_url_prefix);
		self->priv->_url_prefix = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, ccnet_organization_properties[CCNET_ORGANIZATION_URL_PREFIX_PROPERTY]);
	}
}

const gchar*
ccnet_organization_get_creator (CcnetOrganization* self)
{
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_creator;
	result = _tmp0_;
	return result;
}

void
ccnet_organization_set_creator (CcnetOrganization* self,
                                const gchar* value)
{
	gchar* old_value;
	g_return_if_fail (self != NULL);
	old_value = ccnet_organization_get_creator (self);
	if (g_strcmp0 (value, old_value) != 0) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (value);
		_g_free0 (self->priv->_creator);
		self->priv->_creator = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, ccnet_organization_properties[CCNET_ORGANIZATION_CREATOR_PROPERTY]);
	}
}

gint64
ccnet_organization_get_ctime (CcnetOrganization* self)
{
	gint64 result;
	g_return_val_if_fail (self != NULL, 0LL);
	result = self->priv->_ctime;
	return result;
}

void
ccnet_organization_set_ctime (CcnetOrganization* self,
                              gint64 value)
{
	gint64 old_value;
	g_return_if_fail (self != NULL);
	old_value = ccnet_organization_get_ctime (self);
	if (old_value != value) {
		self->priv->_ctime = value;
		g_object_notify_by_pspec ((GObject *) self, ccnet_organization_properties[CCNET_ORGANIZATION_CTIME_PROPERTY]);
	}
}

static void
ccnet_organization_class_init (CcnetOrganizationClass * klass,
                               gpointer klass_data)
{
	ccnet_organization_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &CcnetOrganization_private_offset);
	G_OBJECT_CLASS (klass)->get_property = _vala_ccnet_organization_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_ccnet_organization_set_property;
	G_OBJECT_CLASS (klass)->finalize = ccnet_organization_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_ORGANIZATION_ORG_ID_PROPERTY, ccnet_organization_properties[CCNET_ORGANIZATION_ORG_ID_PROPERTY] = g_param_spec_int ("org-id", "org-id", "org-id", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_ORGANIZATION_EMAIL_PROPERTY, ccnet_organization_properties[CCNET_ORGANIZATION_EMAIL_PROPERTY] = g_param_spec_string ("email", "email", "email", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_ORGANIZATION_IS_STAFF_PROPERTY, ccnet_organization_properties[CCNET_ORGANIZATION_IS_STAFF_PROPERTY] = g_param_spec_int ("is-staff", "is-staff", "is-staff", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_ORGANIZATION_ORG_NAME_PROPERTY, ccnet_organization_properties[CCNET_ORGANIZATION_ORG_NAME_PROPERTY] = g_param_spec_string ("org-name", "org-name", "org-name", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_ORGANIZATION_URL_PREFIX_PROPERTY, ccnet_organization_properties[CCNET_ORGANIZATION_URL_PREFIX_PROPERTY] = g_param_spec_string ("url-prefix", "url-prefix", "url-prefix", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_ORGANIZATION_CREATOR_PROPERTY, ccnet_organization_properties[CCNET_ORGANIZATION_CREATOR_PROPERTY] = g_param_spec_string ("creator", "creator", "creator", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_ORGANIZATION_CTIME_PROPERTY, ccnet_organization_properties[CCNET_ORGANIZATION_CTIME_PROPERTY] = g_param_spec_int64 ("ctime", "ctime", "ctime", G_MININT64, G_MAXINT64, 0, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
}

static void
ccnet_organization_instance_init (CcnetOrganization * self,
                                  gpointer klass)
{
	self->priv = ccnet_organization_get_instance_private (self);
}

static void
ccnet_organization_finalize (GObject * obj)
{
	CcnetOrganization * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CCNET_TYPE_ORGANIZATION, CcnetOrganization);
	_g_free0 (self->priv->_email);
	_g_free0 (self->priv->_org_name);
	_g_free0 (self->priv->_url_prefix);
	_g_free0 (self->priv->_creator);
	G_OBJECT_CLASS (ccnet_organization_parent_class)->finalize (obj);
}

static GType
ccnet_organization_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (CcnetOrganizationClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) ccnet_organization_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (CcnetOrganization), 0, (GInstanceInitFunc) ccnet_organization_instance_init, NULL };
	GType ccnet_organization_type_id;
	ccnet_organization_type_id = g_type_register_static (G_TYPE_OBJECT, "CcnetOrganization", &g_define_type_info, 0);
	CcnetOrganization_private_offset = g_type_add_instance_private (ccnet_organization_type_id, sizeof (CcnetOrganizationPrivate));
	return ccnet_organization_type_id;
}

GType
ccnet_organization_get_type (void)
{
	static volatile gsize ccnet_organization_type_id__once = 0;
	if (g_once_init_enter (&ccnet_organization_type_id__once)) {
		GType ccnet_organization_type_id;
		ccnet_organization_type_id = ccnet_organization_get_type_once ();
		g_once_init_leave (&ccnet_organization_type_id__once, ccnet_organization_type_id);
	}
	return ccnet_organization_type_id__once;
}

static void
_vala_ccnet_organization_get_property (GObject * object,
                                       guint property_id,
                                       GValue * value,
                                       GParamSpec * pspec)
{
	CcnetOrganization * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, CCNET_TYPE_ORGANIZATION, CcnetOrganization);
	switch (property_id) {
		case CCNET_ORGANIZATION_ORG_ID_PROPERTY:
		g_value_set_int (value, ccnet_organization_get_org_id (self));
		break;
		case CCNET_ORGANIZATION_EMAIL_PROPERTY:
		g_value_set_string (value, ccnet_organization_get_email (self));
		break;
		case CCNET_ORGANIZATION_IS_STAFF_PROPERTY:
		g_value_set_int (value, ccnet_organization_get_is_staff (self));
		break;
		case CCNET_ORGANIZATION_ORG_NAME_PROPERTY:
		g_value_set_string (value, ccnet_organization_get_org_name (self));
		break;
		case CCNET_ORGANIZATION_URL_PREFIX_PROPERTY:
		g_value_set_string (value, ccnet_organization_get_url_prefix (self));
		break;
		case CCNET_ORGANIZATION_CREATOR_PROPERTY:
		g_value_set_string (value, ccnet_organization_get_creator (self));
		break;
		case CCNET_ORGANIZATION_CTIME_PROPERTY:
		g_value_set_int64 (value, ccnet_organization_get_ctime (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

static void
_vala_ccnet_organization_set_property (GObject * object,
                                       guint property_id,
                                       const GValue * value,
                                       GParamSpec * pspec)
{
	CcnetOrganization * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, CCNET_TYPE_ORGANIZATION, CcnetOrganization);
	switch (property_id) {
		case CCNET_ORGANIZATION_ORG_ID_PROPERTY:
		ccnet_organization_set_org_id (self, g_value_get_int (value));
		break;
		case CCNET_ORGANIZATION_EMAIL_PROPERTY:
		ccnet_organization_set_email (self, g_value_get_string (value));
		break;
		case CCNET_ORGANIZATION_IS_STAFF_PROPERTY:
		ccnet_organization_set_is_staff (self, g_value_get_int (value));
		break;
		case CCNET_ORGANIZATION_ORG_NAME_PROPERTY:
		ccnet_organization_set_org_name (self, g_value_get_string (value));
		break;
		case CCNET_ORGANIZATION_URL_PREFIX_PROPERTY:
		ccnet_organization_set_url_prefix (self, g_value_get_string (value));
		break;
		case CCNET_ORGANIZATION_CREATOR_PROPERTY:
		ccnet_organization_set_creator (self, g_value_get_string (value));
		break;
		case CCNET_ORGANIZATION_CTIME_PROPERTY:
		ccnet_organization_set_ctime (self, g_value_get_int64 (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

